### ISSUE TITLE
!important

### ISSUE THREAD

**Issue by afiolabi** [winniffy/e-learn#62]
The Webpage has Glitch, you can fix that.

**Comment by winniffy** [comment]
thank you man, still trying to fix things up. could you please specify the issues you noticed? would help a lot. ty

**Comment by THE-AFOLABI** [comment]
> thank you man, still trying to fix things up. could you please specify the issues you noticed? would help a lot. ty

Glitch is actually those extra spaces showed at the sides of the web page... Like it doesn't fit in.

**Comment by THE-AFOLABI** [comment]
> > thank you man, still trying to fix things up. could you please specify the issues you noticed? would help a lot. ty
> 
> Glitch is actually those extra spaces showed at the sides of the web page... Like it doesn't fit in.

![Screenshot_20220315-234926.png](https://user-images.githubusercontent.com/58574822/158485075-dad10e6e-6eb8-4b58-a88b-a4bc53fcc53f.png)
